language: cpp
matrix:
  include:
    - os: windows
      install: choco install mingw
      script: mingw32-make travis
    - os: windows
      install: choco install mingw --version 4.9.3 --force
      script: mingw32-make travis
    - os: windows	
      script: 
        - mkdir build && cd build
        - cmake .. 
        - cmake --build . 