version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  unix:
    docker:
      - image: ubuntu:18.04

        environment:
          CODECOV_TOKEN: 547648b8-b297-4507-8ffc-cbfaf701eac8
          CXX: /usr/bin/g++-8
          CC: /usr/bin/gcc-8

    steps:
      - checkout

      - run:
          name: Install g++-8
          command: "apt-get update && apt-get install -y g++-8"

      - run:
          name: Installing CMAKE
          command: "apt-get install -y cmake"

      - run:
          name: Installing X11
          command: "apt-get install -y libx11-dev"

      - run:
          name: Installing Xrandr
          command: "apt-get install -y libxrandr-dev"

      - run:
          name: Installing OpenGL
          command: "apt-get install -y libgl1-mesa-dev"

      - run:
          name: Installing Openal
          command: "apt-get install -y libopenal-dev"

      - run:
          name: Installing Freetype
          command: "apt-get install -y libfreetype6-dev"

      - run:
          name: Installing Vorbis
          command: "apt-get install -y libvorbis-dev"

      - run:
          name: Installing Perl
          command: "apt-get install -y perl"

      - run:
          name: Install curl
          command: "sudo apt-get install curl"

      - run:
          name: Creating build files
          command: "cmake -H. -Bbuild -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug"

      - run:
          name: Building project
          command: "cmake --build build --config Debug -- -j $(nproc)"

      - run:
          name: Executing tests
          working_directory: "~/project/build"
          command: |
            ctest -j $(nproc) --output-on-failure

      - run:
          name: Uploading coverage
          working_directory: "~/project/build"
          command: |
            ../tools/lcov --directory . --capture --output-file coverage.info --gcov-tool gcov-8
            ../tools/lcov --list coverage.info
            bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

workflows:
  build:
    jobs:
      - unix
